### ISSUE TITLE
[Bug] 콘텐츠 목록 empty 화면 미적용

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#146]
### ISSUE
- Group :  `Front`
- Type : `Bug`
- Detail : 선택한 카테고리에 해당하는 콘텐츠 데이터가 없는 경우 empty 화면 적용 필요

[참고 화면]

![Image](https://github.com/life-secretary/front/assets/64456419/1708e5ac-8ab4-4d03-9e14-cf9c5656c508)

### LABELS
- Estimated time : `md`
- Sprint : ``
- Urgency : `Middle`

**Comment by ciocio97** [comment]
24.06.06 기준 완료했습니다.
