### ISSUE TITLE
[Bug] 검색 화면에서 키보드 입력 후 제출 시 바로 검색되지 않는 현상

### ISSUE THREAD

**Issue by devsoladev** [life-secretary/front#148]
### ISSUE
- Group :  `Front`
- Type : `Bug`
- Detail : 검색 화면의 검색창에서 키보드 입력 후 제출 시 바로 검색되지 않고, 아이콘을 터치해야만 검색이 동작함.

[참고 화면]

![Image](https://github.com/life-secretary/front/assets/64456419/2953702d-7c70-4346-8211-71e539785eae)

### LABELS
- Estimated time : `md`
- Sprint : ``
- Urgency : `Middle`

**Comment by ciocio97** [comment]
24.06.06 기준 완료했습니다.
