### ISSUE TITLE
[Bug] 완료된 할 일 항목에서 항목이 완료 처리되지 않은 것처럼 표시되는 현상

### ISSUE THREAD

**Issue by ciocio97** [life-secretary/front#152]
### ISSUE
- Group :  `Front`
- Type : `Bug`
- Detail : 완료된 항목이니 체크 아이콘으로 표시되면 될 것 같습니다.

### TODO
<img width="358" alt="스크린샷 2024-06-06 오후 7 20 28" src="https://github.com/life-secretary/front/assets/80025242/dfda7117-74f4-4919-a0aa-9c75b8a8b3b9">

### LABELS
- Estimated time : `0.25md`
- Sprint : ``
- Urgency : `Low`

**Comment by devsoladev** [comment]
@ciocio97 님, 현 기획 상 세부 할 일을 모두 체크하지 않아도 완료 처리가 가능합니다. 단, 팝업의 문구가 상이하게 노출됩니다. 

![Image](https://github.com/life-secretary/front/assets/64456419/1f87fe55-aebd-4139-bd64-2dfca405b14f)


![Image](https://github.com/life-secretary/front/assets/64456419/7ea32030-7df9-478d-b223-bb96e8bf395c)

**Comment by devsoladev** [comment]
2024.06.10 해당 이슈는 버그가 아니므로 클로즈 처리하도록 하겠습니다.
