### ISSUE TITLE
[Bug] 완료된 항목 다시 하기 눌렀을 때 완료 리스트에서 제거되지 않는 현상

### ISSUE THREAD

**Issue by ciocio97** [life-secretary/front#153]
### ISSUE
- Group :  `Front`
- Type : `Bug`
- Detail : 할 일 목록으로 재생성은 되지만 완료 리스트에는 남아있습니다.
완료 리스트에서 다시 하기 버튼을 눌렀을 때 완료 리스트에도 남기는 걸로 합의했었나요?
기억이 안나서.. 일단 이슈 남겨놓습니다. 버그가 아닐경우 이슈 삭제 부탁드립니다..!

### TODO
<img width="359" alt="스크린샷 2024-06-06 오후 7 22 47" src="https://github.com/life-secretary/front/assets/80025242/d29d68f4-efa0-4416-a867-c600f1c7411f">

### LABELS
- Estimated time : `1md`
- Sprint : ``
- Urgency : `High`

**Comment by devsoladev** [comment]
현재 할 일 재시작 API가 해당 할 일을 복사하는 구조여서 기존 할 일이 완료 목록에 노출되고 있습니다. 일전에 지혜님과 재시작 시 상태를 변경하도록 수정하는 것으로 이야기 나누었습니다. @bebe217 님, 해당 API 수정 작업 해주시면 될 것 같습니다~
