### ISSUE TITLE
[Bug] 저장 편집버튼 disabled

### ISSUE THREAD

**Issue by bebe217** [life-secretary/front#171]
### ISSUE
- Group :  `Front`
- Type : `Bug`
- Detail : 편집버튼이 비활성화상태
- 한번 누르고 나면 앱이 얼음

### LABELS
- Estimated time : `0.25md`
- Sprint : ``
- Urgency : `Low`

**Comment by devsoladev** [comment]
@bebe217  나의 할 일 편집 버튼이 캡쳐본의 수정하기 버튼을 말씀하시는 걸까요?

![Image](https://github.com/life-secretary/front/assets/64456419/f85e7d8e-4e08-488e-b691-3e68562fef3a)

**Comment by bebe217** [comment]
저장이네요ㅋㅋ 수정했어요
