### ISSUE TITLE
[Bug] 나의 할일 상세화면

### ISSUE THREAD

**Issue by bebe217** [life-secretary/front#175]
### ISSUE
- Group :  `Front`
- Type : `Bug`
- Detail : 1. 할일 추가 및 상태변경시 상단 상세 정보 갱신안됨
- 2. 할일 순서변경 안됨

### LABELS
- Estimated time : `0.25md`
- Sprint : ``
- Urgency : `Middle`

**Comment by devsoladev** [comment]
@bebe217 세부 할 일 drag&drop 기능은 2차 개발 예정입니다. 배포 전에 해당 아이콘 숨김 처리해두겠습니다!
