### ISSUE TITLE
[Feature] Apply /categories API data

### ISSUE THREAD

**Issue by ciocio97** [life-secretary/front#93]
### ISSUE
- Group :  `Front`
- Type : `Feature`
- Detail : 카테고리 api 데이터를 화면에 적용하다

### TODO
1. [x] 카테고리 데이터 바인딩

### LABELS
- Estimated time : `0.25md`
- Sprint : ``
- Urgency : `Low`

**Comment by devsoladev** [comment]
승연님, 제가 HomeScreen 컴포넌트에 카테고리 API 호출 후 recoil state에 세팅하는 로직 구현해두었는데 참고 부탁드립니다!

**Comment by ciocio97** [comment]
> 승연님, 제가 HomeScreen 컴포넌트에 카테고리 API 호출 후 recoil state에 세팅하는 로직 구현해두었는데 참고 부탁드립니다!

네~ 확인했습니다
